order/urls.py
from django.urls import path

from order.views import OrderList, OrderCreate, OrderUpdate, OrderDetailView, OrderActionView

urlpatterns = [
    path('order/', OrderList.as_view(), name='order'),
    path('order_create/', OrderCreate.as_view(), name='order_create'),
    path('order_update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
    path('order_detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order_action/<int:pk>/', OrderActionView.as_view(), name='order_action')
]

payment/urls.py
from django.urls import path

from payment.views import WorkerList, WorkerCreate, WorkerUpdate, CarList, CarUpdate, OutlayCategoryList, \
    OutlayCategoryUpdate, OutlayUpdate, OutlayCategoryDetail, OutlayPaymentCreateView, OutlayPaymentReturnCreateView, \
    ReportsIncomePaymentsView, ReportsOutcomePaymentsView

urlpatterns = [
    path('workers/', WorkerList.as_view(), name='workers'),
    path('worker_create/', WorkerCreate.as_view(), name='worker_create'),
    path('worker_update/<int:pk>/', WorkerUpdate.as_view(), name='worker_update'),
    path('cars/', CarList.as_view(), name='cars'),
    path('car_update/<int:pk>/', CarUpdate.as_view(), name='car_update'),
    path('outlay_cat/', OutlayCategoryList.as_view(), name='outlay_cat'),
    path('outlay_cat_update/<int:pk>/', OutlayCategoryUpdate.as_view(), name='outlay_cat_update'),
    path('outlay_cat_detail/<int:pk>/', OutlayCategoryDetail.as_view(), name='outlay_cat_detail'),
    path('outlay/', OutlayPaymentCreateView.as_view(), name='outlay'),
    path('outlay_update/<int:pk>', OutlayUpdate.as_view(), name='outlay_update'),
    path('return/outlay/payment/create', OutlayPaymentReturnCreateView.as_view(), name='return_outlay'),
    path('report/income/', ReportsIncomePaymentsView.as_view(), name='report_income'),
    path('report/outcome/', ReportsOutcomePaymentsView.as_view(), name='report-outcome'),
]

smart_warehouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('', include('order.urls')),
    path('', include('payment.urls')),
    path('', include('warehouse.urls')),
    path('', include('income.urls')),
    path('', include('counter_party.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.contrib.auth.models import User
from django.db import models

from payment.choices import OUTLAY_TYPE_CHOICES, AMOUNT_TYPE_CHOICES, PAYMENT_LOG_OUTLAY, PAYMENT_METHOD_CHOICES, \
    PAYMENT_TYPE_CHOICES


class Workers(models.Model):
    name = models.CharField(verbose_name='Ф.И.О', max_length=300)
    phone = models.CharField(verbose_name='Номер телефона', max_length=40)
    work_price = models.IntegerField(verbose_name='Зарплата (сумма за 1 день)', null=True, blank=True)
    work_place = models.CharField(verbose_name='Место работы', max_length=40, null=True, blank=True)
    code = models.CharField(verbose_name='Код подтверждения', max_length=50, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class Car(models.Model):
    car_number = models.CharField(verbose_name='Номер машины:', max_length=20)
    driver = models.CharField(verbose_name='Водитель:', max_length=200)
    driver_phone = models.CharField(verbose_name='Контакты водителя:', max_length=400)

    def __str__(self):
        return self.car_number


class OutlayCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование категории расхода')
    type = models.CharField(max_length=255, verbose_name='Тип категории расхода',
                            choices=OUTLAY_TYPE_CHOICES, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория затрат'
        verbose_name_plural = 'Категории затрат'


class OutLay(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')
    outlay_type = models.ForeignKey('OutlayCategory',
                                    on_delete=models.PROTECT,
                                    verbose_name='Категории',
                                    null=True,
                                    blank=True)
    name = models.CharField(max_length=255, verbose_name='Причина')

    def __str__(self):
        return self.name


class PaymentLog(models.Model):
    """
        Таблица оплат
    """
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    amount = models.FloatField(default=0, verbose_name='Сумма')
    payment_type = models.CharField(max_length=10,
                                    verbose_name='Тип валюты',
                                    choices=PAYMENT_TYPE_CHOICES,
                                    default='cash')
    payment_method = models.CharField(max_length=10,
                                      verbose_name='Метод оплаты',
                                      choices=PAYMENT_METHOD_CHOICES,
                                      default='usd')
    outcat = models.IntegerField(default=0)
    outlay = models.IntegerField(default=0)
    outlay_child = models.IntegerField(default=0)
    user = models.ForeignKey(User,
                             on_delete=models.PROTECT,
                             verbose_name='Пользователь')
    comment = models.TextField(null=True,
                               blank=True)
    aor = models.BooleanField(default=False)
    amount_type = models.CharField(max_length=10,
                                   verbose_name='Тип валюты',
                                   choices=AMOUNT_TYPE_CHOICES)
    payment_log_type = models.CharField(max_length=255, verbose_name='Расход/Доход')
    rate = models.FloatField(default=0,
                             verbose_name='Курс доллара')


class Cashier(models.Model):
    amount = models.FloatField(default=0,
                               verbose_name='Сумма')
    payment_type = models.CharField(max_length=10,
                                    verbose_name='Тип валюты',
                                    choices=PAYMENT_TYPE_CHOICES,
                                    default='usd')

    def __str__(self):
        return self.payment_type


class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super(SingletonModel, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1)
        return obj


class ProjectSetting(SingletonModel):
    rate = models.FloatField(default=0)

    def __str__(self):
        return str(self.rate)

payment/forms.py
from django import forms

from payment.choices import EXPENSE_PAYMENT_TYPE_CHOICES, PAYMENT_METHOD_CHOICES
from payment.models import OutlayCategory, OutLay, Car, Workers


class WorkerCreateForm(forms.ModelForm):
    class Meta:
        model = Workers
        fields = ('name', 'phone', 'work_price', 'work_place', 'code',)


class OutlayCategoryForm(forms.ModelForm):
    class Meta:
        model = OutlayCategory
        fields = 'name', 'type'


class OutLayForm(forms.ModelForm):
    class Meta:
        model = OutLay
        fields = 'name',


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'


class OutlayPaymentForm(forms.Form):
    outlay_category = forms.ModelChoiceField(label='Категория расхода', queryset=OutlayCategory.objects.all(),
                                             required=True)
    outlay_type = forms.ModelChoiceField(label='Причина', queryset=OutLay.objects.all(), required=True)
    worker = forms.ModelChoiceField(label='Сотрудник', queryset=Workers.objects.all(), required=True)
    car = forms.ModelChoiceField(label='Машина', queryset=Car.objects.all(), required=True)
    payment_amount = forms.FloatField(label='Сумма расхода')
    comment = forms.CharField(label='Комментарии', required=False)
    payment_type = forms.ChoiceField(label='Тип оплаты', choices=EXPENSE_PAYMENT_TYPE_CHOICES)
    payment_method = forms.ChoiceField(label='Метод оплаты', choices=PAYMENT_METHOD_CHOICES)


class ReportOutcomeForm(forms.Form):
    outlay_category = forms.ModelChoiceField(label='Категория расхода', queryset=OutlayCategory.objects.all(),
                                             required=True)
    worker = forms.ModelChoiceField(label='Сотрудник', queryset=Workers.objects.all(), required=False)
    car = forms.ModelChoiceField(label='Машина', queryset=Car.objects.all(), required=False)

payment/templates/outlay.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Добавить расход</h4>
                        </div>
                    </div>
                    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    </div>
                </div>
                <form class="row row-cols-3 justify-content-end" method="post">
                    {% csrf_token %}
                    {% for f in outlay_payment_form %}
                        {% if f.errors %}{% for error in f.errors %} {{ error|escape }}
                        {% endfor %}{% endif %}
                        {% if f.name == 'outlay_category' %}
                            <div class="col-md-12 row pl-0">
                                <div id="id_{{ f.name }}_input_group" class="col-md pl-0">
                                    {{ f.label_tag }}
                                    <select name="outlay_category" onchange="changeForm(this)"
                                            autocomplete="off" class="form-control"
                                            required="" id="id_outlay_category">
                                        <option value="" selected="selected">---------</option>
                                        {% for outlay_category in outlay_categories %}
                                            <option value="{{ outlay_category.id }}"
                                                    data_type="{{ outlay_category.type }}">{{ outlay_category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                {% elif f.name == 'outlay_type' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md pl-0">
                                    {{ f.label_tag }}
                                    <select name="outlay_type"
                                            autocomplete="off" class="form-control"
                                            required="" id="id_outlay_type">
                                        <option value="" selected="selected">---------</option>
                                        {% for outlay in outlay_type %}
                                            <option id="id_outlay_option_{{ outlay.id }}"
                                                    value="{{ outlay.id }}"
                                                    data_type="{{ outlay.outlay_type.pk }}">{{ outlay.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <div id="hidden-option" class="d-none">

                                    </div>
                                </div>
                                {% elif f.name == 'worker' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                                {% elif f.name == 'car' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                            </div>
                            <div class="col-12 row pl-0 mt-2">
                                {% elif f.name == 'payment_amount' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                                {% elif f.name == 'comment' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                            </div>
                            <div class="col-md-12 row pl-0 mt-2">
                                {% elif f.name == 'payment_type' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                                {% elif f.name == 'payment_method' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                                <div class="col-md-4 mt-2">
                                    <button class="btn btn-primary ml-auto mt-4 float-right" type="submit">
                                        Добавить
                                    </button>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Расходы</h4>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm mb-0">
                        <thead>
                        <tr>
                            <th class="align-middle">Юзер</th>
                            <th class="align-middle">Смма</th>
                            <th class="align-middle">Описание</th>
                            <th class="align-middle">Создание</th>
                        </tr>
                        </thead>
                        {% for payment_log in payment_logs %}
                            <tr class="btn-ravel-trigger">
                                <td class="py-2 mb-2">{{ payment_log.user }}</td>
                                {% if payment_log.payment_type == 'uzs' %}
                                    <td class="p-1">{{ payment_log.amount }} сум</td>
                                {% elif payment_log.payment_type == 'usd' %}
                                    <td class="p-1">{{ payment_log.amount }} $</td>
                                {% endif %}
                                <td class="py-2">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-outline-light btn-sm mb-2"
                                            data-toggle="modal"
                                            data-target="#exampleModalLong{{ payment_log.id }}">ЕЩЕ
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade"
                                         id="exampleModalLong{{ payment_log.id }}">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Описание</h5>
                                                    <button type="button" class="close"
                                                            data-dismiss="modal">
                                                        <span>&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p class="text-black">{{ payment_log.comment }}</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button"
                                                            class="btn btn-danger light"
                                                            data-dismiss="modal">Закрыть
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="py-2">{{ payment_log.created }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script>
        $(document).ready(function () {
            inputGroupDisable()
        });

        function inputGroupDisable() {
            $('#id_car_input_group').addClass('d-none');
            $('#id_car').attr('disabled', 'disabled');
            $('#id_worker_input_group').addClass('d-none');
            $('#id_worker').attr('disabled', 'disabled');
            $('#id_outlay_type').children('option').appendTo('#hidden-option')
        }

        function changeForm(element) {
            inputGroupDisable();
            let type = $(`#${element.id}`).children('option:selected').attr('data_type')
            if (type === 'car') {
                $('#id_car_input_group').removeClass('d-none');
                $('#id_car').removeAttr('disabled');
            }
            if (type === 'worker') {
                $('#id_worker_input_group').removeClass('d-none');
                $('#id_worker').removeAttr('disabled');
            }
            let transfer_list = [];
            for (let elem = 0; elem < $('#hidden-option').children().length; elem++) {
                if (`${$('#hidden-option').children()[elem].getAttribute('data_type')}` === `${$('#id_outlay_category').children('option:selected').val()}`) {
                    transfer_list.push(`#${$('#hidden-option').children()[elem].id}`);
                }
            }
            for (let element of transfer_list) {
                $(element).appendTo('#id_outlay_type');
            }
        }
    </script>
{% endblock %}

payment/templates/return_outlay_create.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="container-fluid">
        <div class="card">
            <div class="card-body">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Возврат</h4>
                        </div>
                    </div>
                    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    </div>
                </div>
                <form class="row row-cols-3 justify-content-end" method="post">
                    {% csrf_token %}
                    {% for f in outlay_payment_form %}
                        {% if f.errors %}{% for error in f.errors %} {{ error|escape }}
                        {% endfor %}{% endif %}
                        {% if f.name == 'outlay_category' %}
                            <div class="col-md-12 row pl-0">
                                <div id="id_{{ f.name }}_input_group" class="col-md pl-0">
                                    {{ f.label_tag }}
                                    <select name="outlay_category" onchange="changeForm(this)"
                                            autocomplete="off" class="form-control"
                                            required="" id="id_outlay_category">
                                        <option value="" selected="selected">---------</option>
                                        {% for outlay_category in outlay_categories %}
                                            <option value="{{ outlay_category.id }}"
                                                    data_type="{{ outlay_category.type }}">{{ outlay_category.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                {% elif f.name == 'outlay_type' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md pl-0">
                                    {{ f.label_tag }}
                                    <select name="outlay_type"
                                            autocomplete="off" class="form-control"
                                            required="" id="id_outlay_type">
                                        <option value="" selected="selected">---------</option>
                                        {% for outlay in outlay_type %}
                                            <option id="id_outlay_option_{{ outlay.id }}"
                                                    value="{{ outlay.id }}"
                                                    data_type="{{ outlay.outlay_type.pk }}">{{ outlay.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <div id="hidden-option" class="d-none">

                                    </div>
                                </div>
                                {% elif f.name == 'worker' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                                {% elif f.name == 'car' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                            </div>
                            <div class="col-12 row pl-0 mt-2">
                                {% elif f.name == 'payment_amount' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                                {% elif f.name == 'comment' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                            </div>
                            <div class="col-md-12 row pl-0 mt-2">
                                {% elif f.name == 'payment_type' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                                {% elif f.name == 'payment_method' %}
                                <div id="id_{{ f.name }}_input_group" class="col-md-4 pl-0">
                                    {{ f.label_tag }}
                                    {{ f|add_class:'form-control'|attr:'autocomplete:off' }}
                                </div>
                                <div class="col-md-4 mt-2">
                                    <button class="btn btn-primary ml-auto mt-4 float-right" type="submit">
                                        Добавить
                                    </button>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </form>
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Расходы</h4>
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm mb-0">
                        <thead>
                        <tr>
                            <th class="align-middle">Юзер</th>
                            <th class="align-middle">Смма</th>
                            <th class="align-middle">Описание</th>
                            <th class="align-middle">Создание</th>
                        </tr>
                        </thead>
                        {% for payment_log in payment_logs %}
                            <tr class="btn-ravel-trigger">
                                <td class="py-2 mb-2">{{ payment_log.user }}</td>
                                {% if payment_log.payment_type == 'uzs' %}
                                    <td class="p-1">{{ payment_log.amount }} сум</td>
                                {% elif payment_log.payment_type == 'usd' %}
                                    <td class="p-1">{{ payment_log.amount }} $</td>
                                {% endif %}
                                <td class="py-2">
                                    <!-- Button trigger modal -->
                                    <button type="button" class="btn btn-outline-light btn-sm mb-2"
                                            data-toggle="modal"
                                            data-target="#exampleModalLong{{ payment_log.id }}">ЕЩЕ
                                    </button>
                                    <!-- Modal -->
                                    <div class="modal fade"
                                         id="exampleModalLong{{ payment_log.id }}">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title">Описание</h5>
                                                    <button type="button" class="close"
                                                            data-dismiss="modal">
                                                        <span>&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p class="text-black">{{ payment_log.comment }}</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button"
                                                            class="btn btn-danger light"
                                                            data-dismiss="modal">Закрыть
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td class="py-2">{{ payment_log.created }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script>
        $(document).ready(function () {
            inputGroupDisable()
        });

        function inputGroupDisable() {
            $('#id_car_input_group').addClass('d-none');
            $('#id_car').attr('disabled', 'disabled');
            $('#id_worker_input_group').addClass('d-none');
            $('#id_worker').attr('disabled', 'disabled');
            $('#id_outlay_type').children('option').appendTo('#hidden-option')
        }

        function changeForm(element) {
            inputGroupDisable();
            let type = $(`#${element.id}`).children('option:selected').attr('data_type')
            if (type === 'car') {
                $('#id_car_input_group').removeClass('d-none');
                $('#id_car').removeAttr('disabled');
            }
            if (type === 'worker') {
                $('#id_worker_input_group').removeClass('d-none');
                $('#id_worker').removeAttr('disabled');
            }
            let transfer_list = [];
            for (let elem = 0; elem < $('#hidden-option').children().length; elem++) {
                if (`${$('#hidden-option').children()[elem].getAttribute('data_type')}` === `${$('#id_outlay_category').children('option:selected').val()}`) {
                    transfer_list.push(`#${$('#hidden-option').children()[elem].id}`);
                }
            }
            for (let element of transfer_list) {
                $(element).appendTo('#id_outlay_type');
            }
        }
    </script>
{% endblock %}