counter_party/urls.py
from django.urls import path

from counter_party.views import CounterPartyView, CounterPartyCreateView, CounterPartyDetailView, CounterPartyUpdate

urlpatterns = [
    path('counter_party/list', CounterPartyView.as_view(), name='counter_party'),
    path('counter_party/create', CounterPartyCreateView.as_view(), name='counter_party_create'),
    path('counter_party/detail/<int:pk>/', CounterPartyDetailView.as_view(), name='counter_party_detail'),
    path('counter_party/update/<int:pk>/', CounterPartyUpdate.as_view(), name='counter_party_update')
]

order/urls.py
from django.urls import path

from order.views import OrderList, OrderCreate, OrderUpdate, OrderDetailView, OrderActionView

urlpatterns = [
    path('order/', OrderList.as_view(), name='order'),
    path('order_create/', OrderCreate.as_view(), name='order_create'),
    path('order_update/<int:pk>/', OrderUpdate.as_view(), name='order_update'),
    path('order_detail/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order_action/<int:pk>/', OrderActionView.as_view(), name='order_action')
]

smart_warehouse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('', include('order.urls')),
    path('', include('payment.urls')),
    path('', include('warehouse.urls')),
    path('', include('income.urls')),
    path('', include('counter_party.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

counter_party/models.py
from django.db import models
from django.contrib.auth.models import User
from counter_party.choices import CONTR_AGENT_STATUS_CHOICES


class CounterParty(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя', unique=True)
    balance_usd = models.FloatField(default=0,
                                    verbose_name='USD')
    balance_uzs = models.FloatField(default=0,
                                    verbose_name='UZS')
    org_name = models.CharField(max_length=255, verbose_name='Название организации', null=True, blank=True)
    phone = models.CharField(max_length=255, verbose_name='Номер телефона', unique=True)
    phone2 = models.CharField(max_length=255, verbose_name='Дополнительный номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адресс', null=True, blank=True)
    inn = models.CharField(max_length=255, verbose_name='ИНН', null=True, blank=True)
    email = models.EmailField(verbose_name='E-mail', null=True, blank=True)
    status = models.IntegerField(choices=CONTR_AGENT_STATUS_CHOICES, verbose_name='Статус', default=0)
    sms_live = models.CharField(max_length=255, verbose_name='sms', null=True, blank=True)
    extra_info = models.TextField(verbose_name='Описание контр агента', null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Пользователь', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        if not self.org_name:
            org_name = '-'
        else:
            org_name = self.org_name
        return f"{self.name} | {org_name} | {self.phone}"

    class Meta:
        verbose_name = 'Контр агент'
        verbose_name_plural = 'Контр агенты'

counter_party/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, TemplateView, UpdateView

from counter_party.models import CounterParty


class CounterPartyView(ListView):
    template_name = 'counter_party_list.html'
    model = CounterParty

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CounterPartyView, self).get_context_data(**kwargs)
        context['contr_agents'] = CounterParty.objects.all
        return context


class CounterPartyCreateView(CreateView):
    template_name = 'counter_party_create.html'
    model = CounterParty
    fields = ['name', 'org_name', 'phone', 'phone2', 'address', 'inn', 'email', 'status', 'sms_live', 'extra_info',
              'user']
    success_url = '/counter_party/list'


class CounterPartyDetailView(TemplateView):
    template_name = 'counter_party_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CounterPartyDetailView, self).get_context_data(**kwargs)
        counter_party = CounterParty.objects.get(id=self.kwargs['pk'])
        context['contr_agent'] = counter_party
        return context


class CounterPartyUpdate(UpdateView):
    template_name = 'counter_party_update.html'
    model = CounterParty
    fields = ['name', 'org_name', 'phone', 'phone2', 'address', 'inn', 'email', 'status', 'sms_live', 'extra_info',
              'user']
    success_url = '/counter_party/list'

    def get_success_url(self):
        back_url = self.request.GET.get('back_url', None)
        pk = self.request.GET.get('pk', None)
        if back_url and pk:
            return reverse(back_url, kwargs={'pk': pk})
        elif back_url:
            return reverse(back_url)
        else:
            return reverse('counter_party')

counter_party/templates/counter_party_create.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Добавить Агент</h4>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
            </div>
        </div>
        <form class="card" action="" method="post">
            <div class="card-body row">
                {% csrf_token %}
                {% for f in form %}
                    <div class="col-md-4 mt-2">
                        {{ f.label_tag }}
                        {{ f|add_class:'form-control'|attr:'rows:1' }}
                    </div>
                {% endfor %}
                <div class="col align-self-end">
                    <button class="btn btn-block btn-primary mt-2 float-right" type="submit">Добавить</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

counter_party/templates/counter_party_detail.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row page-titles mx-0 py-4">
            <div class="col welcome-text">
                <h3 class="text-primary m-0">Агент: {{ contr_agent.name }}</h3>
            </div>

            <div class="dropdown">
                <button type="button" class="btn btn-primary sharp" data-toggle="dropdown" aria-expanded="false">
                    <svg width="20px" height="20px" viewBox="0 0 24 24" version="1.1">
                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <rect x="0" y="0" width="24" height="24"></rect>
                            <circle fill="#fff" cx="5" cy="12" r="2"></circle>
                            <circle fill="#fff" cx="12" cy="12" r="2"></circle>
                            <circle fill="#fff" cx="19" cy="12" r="2"></circle>
                        </g>
                    </svg>
                </button>
                <div class="dropdown-menu" x-placement="bottom-start"
                     style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 33px, 0px);">
                    <ul>
                        <li>
                            <form class="text-center" action="{% url 'counter_party_update' contr_agent.pk %}"
                                  id="agent_delete"
                                  method="get">
                                <input type="hidden" name="back_url" value="counter_party_detail">
                                <input type="hidden" name="pk" value="{{ contr_agent.id }}">
                                <button type="submit"
                                        class="btn btn-transparent">
                                    Редактировать
                                </button>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <div class="col-lg-12">
                            <div class="table-responsive">
                                <table class="table table-bordered table-sm table-hover table-striped">

                                    <tbody>
                                    <tr>
                                        <table id="w0" class="table table-striped table-bordered detail-view">
                                            <tbody>
                                            <tr>
                                                <th>Статус</th>
                                                <td>{{ contr_agent.get_status_display|default:'-' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Название организации</th>

                                                <td>{{ contr_agent.org_name|default:'-' }}</td>
                                            </tr>

                                            <tr>
                                                <th>Номер телефона</th>
                                                <td>{{ contr_agent.phone|default:'-' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Создано</th>
                                                <td>{{ contr_agent.created_at|default:'-' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Информация</th>
                                                <td>{{ contr_agent.extra_info|default:'-' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Пользователь</th>
                                                <td>{{ contr_agent.user|default:'-' }}</td>
                                            </tr>
                                            </tbody>
                                        </table>

                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-md-4">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Баланс</h4>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered table-sm table-hover table-striped">
                                <tbody>
                                <tr>
                                    <td class="">Сум</td>
                                    <td class="divide">{{ contr_agent.balance_uzs }}</td>
                                </tr>
                                <tr>
                                    <td class="">Доллар</td>
                                    <td class="divide">{{ contr_agent.balance_usd }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

counter_party/templates/counter_party_list.html
{% extends 'layouts/base.html' %}

{% block content %}
<div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Агенты</h4>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'counter_party_create' %}">Добавить</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)"></a></li>
                </ol>
            </div>
        </div>
        <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm mb-0">
                    <thead>
                        <tr>
                            <th class="align-middle">Ф.И.О</th>
                            <th class="align-middle pr-7">Организация</th>
                            <th class="align-middle">Номер телефона</th>
                            <th class="align-middle">Баланс (доллар)</th>
                            <th class="align-middle">Баланс (сумм)</th>
                        </tr>
                    </thead>
                        {% for contr_agent in contr_agents %}
                            <tr class="btn-ravel-trigger">
                                <td class="py-2 mb-2">{{ contr_agent.name }}</td>
                                <td class="py-2">{{ contr_agent.org_name }}</td>
                                <td class="py-2">{{ contr_agent.phone }}</td>
                                <td class="py-2">{{ contr_agent.balance_usd }}</td>
                                <td class="py-2">{{ contr_agent.balance_uzs }}</td>
                                <td class="py-2">{{ contr_agent.created_at|date:"SHORT_DATE_FORMAT" }}</td>
                                <td class="py-2"><a href="{% url 'counter_party_update' contr_agent.pk %}"><i class="fa fa-pencil"></i></a></td>
                                <td class="py-2"><a href="{% url 'counter_party_detail' contr_agent.pk %}"><i class="fas fa-eye"></i></a></td>
                            </tr>
                        {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

counter_party/templates/counter_party_update.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h4>Изменить Агент</h4>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
            </div>
        </div>
        <form class="card" action="" method="post">
            <div class="card-body row">
                {% csrf_token %}
                {% for f in form %}
                    <div class="col-md-4 mt-2">
                        {{ f.label_tag }}
                        {{ f|add_class:'form-control'|attr:'rows:1' }}
                    </div>
                {% endfor %}
                <div class="col align-self-end">
                    <button class="btn btn-block btn-primary mt-2 float-right" type="submit">Добавить</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}